---
- name: "Deploy EKS"
  hosts: webserver1811[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
 
  roles:
    - capstone-deployment
    - capstone-service
