---
- name: "Deploy Green version"
  hosts: webservertest[1]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
 
  roles:
    - capstone-green
