---
- name: Update the deployment to run the latest Build
  shell: "./bin/kubectl set image deployments/capstone capstone=sarahlyne46/capstone:{{ CIRCLE_WORKFLOW_ID }}"
    args:
      chdir: $HOME
