- name: Copy deployment configuration
  copy:
    src: "app-blue.yml"
    dest: $HOME
- name: Update the deployment to run the latest Build
  shell: "./bin/kubectl set image deployments/capstone-project-deployment capstone-project-app=sarahlyne46/capstone:{{ CIRCLE_WORKFLOW_ID }}"
    args:
      chdir: $HOME
