- name: Copy deployment configuration
  copy:
    src: "app-blue.yml"
    dest: $HOME

- name: Check deployments
  shell: "./bin/kubectl get deployments"
  args:
    chdir: $HOME

- name: Check pods
  shell: "./bin/kubectl get pods -o wide"
  args:
    chdir: $HOME

- name: Check nodes
  shell: "./bin/kubectl get nodes -o wide"
  args:
    chdir: $HOME
    
- name: Describe pods
  shell: "./bin/kubectl describe pods"
  args:
    chdir: $HOME
    
- name: Apply deployment configuration
  shell: "./bin/kubectl apply -f app-blue.yml"
  args:
    chdir: $HOME
