#!/usr/bin/env bash

# Download kubernetes & install
curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
sudo apt-get update && sudo apt-get install docker.io -y



# confirm docker version
docker --version
sudo apt-get update && sudo apt-get install docker.io -y
