- name: Copy service configuration
  copy:
    src: "app-service.yml"
    dest: $HOME

- name: Create service configuration
  command: "./bin/kubectl apply -f app-service.yml"
  args:
    chdir: $HOME   
    
- name: wait for 2 mins
  shell: sleep 120
  
  
- name: check elb setup
  command: kubectl describe service my-elb-service
  args:
    chdir: $HOME
