- name: Copy service configuration
  copy:
    src: "app-service.yml"
    dest: $HOME

- name: Create service configuration
  command: "./bin/kubectl apply -f app-service.yml"
  args:
    chdir: $HOME   
    
- name: wait for 30 secs
  shell: sleep 30
  
  
- name: Describe pods
  shell: "./bin/kubectl describe service capstone-project-service"
  args:
    chdir: $HOME
