Description:
    Sarah Lyne / Udacity Capstone Project / AWS Cloud DevOps Course
    Creates the nodegroup for the Amazon EKS Cluster

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: capstone-project-ubuntu

  MinSize:
    Description: Minimum number of web application servers
    Default: 2
    Type: String

  MaxSize:
    Description: Maximum number of web application servers
    Default: 6
    Type: String

  DesiredSize:
    Description: How many instances should be created.
    Default: 4
    Type: Number

  KeyPairName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Default: udacity
    Type: AWS::EC2::KeyPair::KeyName


Resources:
  NodeInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${EnvironmentName}-nodegroup-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !FindInMap [ServicePrincipals, !Ref "AWS::Partition", ec2]
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      Path: /


  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Sub ${EnvironmentName}-cluster
      NodeRole: !GetAtt NodeInstanceRole.Arn
      NodegroupName: !Sub ${EnvironmentName}-nodegroup
      ScalingConfig:
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize
        DesiredSize: !Ref DesiredSize
      Subnets:
        Fn::Split:
          - ","
          - Fn::ImportValue:
              Fn::Sub: ${EnvironmentName}-PUB-NETS
      Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName}-EKSNodes
        
Outputs:
  NodeInstanceRole:
    Description: The node instance role
    Value: !GetAtt NodeInstanceRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-IR
  NodeGroup:
    Description: The node group for EKS
    Value: !Ref NodeGroup
    Export:
      Name: !Sub ${EnvironmentName}-NG
