Description: >
  Capstone webservers
  
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: capstone-project-ubuntu

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Webservers
      GroupDescription: Allow port 22 and post 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          

  EC2Instanceblue:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: capstone 
      ImageId: ami-020db2c14939a8efb    # ubuntu 18.04 in region us-east-2
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-blue
        - Key: Project
          Value: !Ref EnvironmentName

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: capstone 
      ImageId: ami-020db2c14939a8efb    # ubuntu 18.04 in region us-east-2
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-green
        - Key: Project
          Value: !Ref EnvironmentName


  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "sl-capstone-website-ubuntu"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  
  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]


Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL for website hosted on S3      
