version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0


jobs:
  install-eksctl:
    executor: aws-eks/python3
    steps:
      - run:
        name: Install the eksctl tool
        command: |
          if which eksctl > /dev/null; then
          echo "eksctl is already installed"
          exit 0
          fi
          mkdir -p eksctl_download
          curl --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
          | tar xz -C eksctl_download
          chmod +x eksctl_download/eksctl
          SUDO=""
          if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
            SUDO="sudo"
          fi
          $SUDO mv eksctl_download/eksctl /usr/local/bin/
          rmdir eksctl_download
  
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
          name: Test cluster

workflows:
  deployment:
    jobs:
      - install-eksctl
      - aws-eks/create-cluster:
          cluster-name: my-eks-demo
          requires:
            - install-eksctl        
      - test-cluster:
          cluster-name: my-eks-demo
          requires:
            - aws-eks/create-cluster