apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-deployment
  labels:
    app: capstone-project-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: capstone-project-app
  template:
    metadata:
      labels:
        app: capstone-project-app
    spec:
      containers:
        - name: capstone-project-app
          image: sarahlyne46/capstone-test:2211-test
          ports:
            - containerPort: 80
