apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
  labels:
    app: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: sarahlyne46/capstone-test:1811-test
          ports:
            - containerPort: 80
