apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  type: LoadBalancer
  selector:
    run: capstone-project-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
