apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-project-deployment
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP