apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  selector:
    app: capstone-project-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9376
  type: LoadBalancer