apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  type: LoadBalancer
  selector:
    run: capstone-project
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
