apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  selector:
    app: app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer